name: tests

on:
  push:
    branches:
      - main
      - develop
    paths-ignore:
      - "**.md"

  pull_request:
    branches:
      - main
      - develop
    paths-ignore:
      - "**.md"

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: extractions/setup-just@v1
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          components: rustfmt, clippy
      - run: just prepare
      - run: just check-lint
      - run: just test
